services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      WAIT_HOSTS: db:3306
      WAIT_TIMEOUT: 30
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      MAIL_FROM: no-reply@minierp.local

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 10

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  db_data:
